name: Build Enzo Mod
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          # This command creates the missing engine files automatically
          gradle wrapper
          chmod +x gradlew
          # This starts the actual mod building
          ./gradlew build

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: EnzoModKit-Jar
          path: build/libs/*.jar
          
